### ISSUE TITLE
jsoncsv depends on flatiron

### ISSUE THREAD

**Issue by twilson63** [gradus/jsoncsv#1]
Why does jsoncsv depend on flatiron, shouldn't the module have as few dependencies as possible, I am concerned about potential conflicts with other frameworks and when including the package it adds a lot of weight/modules that I won't be using.  Is there anyway to abstract the cli from the actual library so that it can be used in a modular way without having to add all the cli functionality?

**Comment by gradus** [comment]
convert.js and cli.js can be removed entirely as well as bin/jsoncsv.
the cli tool is not yet functional and now would be a good time to remove it.
That would reduce our dependencies to nothing.
If you feel that is the right direction, I can make the changes.

**Comment by gradus** [comment]
@twilson63 I made you a collaborator on this project.

**Comment by gradus** [comment]
@twilson63 I ripped out all of the cli code and republished as v0.1.0 
There now are only dev dependencies.

**Comment by twilson63** [comment]
Awesome

Thx

Tom

Sent from my iPhone

On Mar 13, 2012, at 7:05 PM, Kris Windham
reply@reply.github.com
wrote:

**Comment by gradus** [comment]
had to make a small patch.
actually, it is version 0.1.1 now.
The dependency is set specifically to 0.1.1 in package.json for the project where this module is used.
